development:
  adapter: postgresql
  encoding: unicode
  database: serenity_development
  pool: 5
  host: localhost
  username: serenity
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: serenity_test
  pool: 5
  host: localhost
  username: serenity
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: serenity
  pool: 5
  host: localhost
  username: serenity
  password: Figaro.env.postgres_password
  timeout: 5000